### ISSUE TITLE
Error 403 Account deactivated on `terraform apply`

### ISSUE THREAD

**Issue by dmytro** [terraform-providers/terraform-provider-acme#9]
I am using Terraform `acme` provider with `acme_certificate` and `acme_registration` resources for several domains. This setup worked for the past few weeks. Since few days ago when running `terraform apply` on some of the domains I receive 403 error. Now I cannot use neither `apply` nor `apply` on these setups.

Error I'm receiving (formatted for readability):
```
* module.vpn.module.paidy-openvpn.acme_registration.reg: acme_registration.reg: 
    acme: Error 403 - urn:ietf:params:acme:error:unauthorized - 
    Account is not valid, has status "deactivated"
```

Is there any way to clear there errors?

**Comment by tommymccallig** [comment]
We've run into the same issue. It seems to have been caused by the fact that when you do a destroy, the module will deactivate your account as per https://tools.ietf.org/html/draft-ietf-acme-acme-18#section-7.5.2 .

Does anyone have any thoughts on a less destructive way of achieving a destroy?

**Comment by vancluever** [comment]
@tommymccallig this is exactly how you should do it. As the `acme_registration` resource does manage the full lifecycle of a user and since 1.0 has supported actual deletion of the registration on destroy, you should be managing your registrations under a different configuration as your certificates, or out of band.

@dmytro to answer your original question, if the account has been deactivated, your main recourse is to create another one. Let's encrypt has pretty generous rate limits for accounts which you can see [here](https://letsencrypt.org/docs/rate-limits/). From there it's pretty trivial to get new certificates.

**Comment by cpu** [comment]
> @dmytro to answer your original question, if the account has been deactivated, your main recourse is to create another one. Let's Encrypt has pretty generous rate limits for accounts which you can see [here](https://letsencrypt.org/docs/rate-limits/). From there it's pretty trivial to get new certificates.

To add a bit more context here this is the _only_ recourse I know of. The [ACME draft specification](https://tools.ietf.org/html/draft-ietf-acme-acme-18#section-7.3.6) explicitly calls out that account deactivation is irreversible:
> ACME does not provide a way to reactivate a deactivated account.
